### ISSUE TITLE
After what condition will it send the mail

### ISSUE THREAD

**Issue by Pranjal705** [RahulPalve/Android-keylogger-with-email#2]
i have cloned the project and i want to test it, followed all the instructions given, but the mail isn't coming.

**Comment by RahulPalve** [comment]
try this [Gmail SMTP Restrictions](https://help.groovehq.com/help/why-wont-my-gmail-smtp-settings-work#:~:text=In%20Google%20Mail%2C%20you%20must,this%20setting%20must%20be%20enabled%3A&text=Please%20note%20that%20these%20options,enabled%20for%20your%20Google%20account.), also if you are facing any error comment here

**Comment by Pranjal705** [comment]
Thanks brother, it worked, i turned the 2 factor authentication and allowed the less secure apps.

**Comment by manasesnganga** [comment]
Hello, after how long is the Logger app sending the logs?
